### PR TITLE
Fix runtime configuration on startup in cloud

### LINKED ISSUE #10: peform_runtime_config fails during Drupal startup
For static/cloud instances, [perform_runtime_config](https://github.com/jhu-idc/idc-isle-buildkit/blob/main/drupal/rootfs/etc/cont-init.d/99-custom-setup.sh#L160) fails due to errors like:
```
 [error]  Error: Cannot create references to/from string offsets in Drupal\Component\Utility\NestedArray::setValue() (line 155 of /var/www/drupal/web/core/lib/Drupal/Component/Utility/NestedArray.php) #0 /var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigBase.php(192): Drupal\Component\Utility\NestedArray::setValue(Array, Array, NULL)
drupal_1      | #1 /var/www/drupal/web/core/lib/Drupal/Core/Config/Config.php(184): Drupal\Core\Config\ConfigBase->set('gemini_url.http...', NULL)
```

Fix the issue, or find an alternate way of performing the configuration (e.g. via settings.php).  As of #9 , this error will be permitted to occur without causing Drupal container termination as an exception to the rule.

### PR DESCRIPTION
**Pull request by emetsger**
Correct parameters supplied to `perform_runtime_config`.

Closes #10 

## To test
1. Build images (`./gradlew build`), copy the newly created image tag.
1. Head over to `idc-isle-dc` and set the value of TAG in `.env`
1. Execute `make static-docker-compose.yml`.  If a cached (previously built) image exists, remove it and re-run the make command.
1. Edit `docker-compose.yml` and add `DRUPAL_IGNORE_STARTUP_ERRORS: "true"` to the `drupal` `environment`.
1. `make up`
1. Tail startup log of `drupal` and observe that whilst config-import fails, the runtime configuration succeeds
1. Proceed to create a repository item (say an image) with the Open Sea Dragon display hint selected, then add an Image Media with use `Preservation Master File`.  Observe that the thumbnail and service derivatives are created.   Observe that OSD works.

### CODE REVIEW

**Comment by emetsger** [comment]
Will need to be rebased after #9 is merged.

**Comment by birkland** [comment]
OK, I just merged, so it is safe to rebase

**Comment by emetsger** [comment]
rebased!

File: drupal/rootfs/etc/cont-init.d/99-custom-setup.sh [hunk 1]
```diff
@@ -163,7 +162,7 @@ function main {
   if [ -n "${DRUPAL_INSTANCE}" ] && [ "${DRUPAL_INSTANCE}" != "dev" ] ;
   then
     # TODO:  This fails and needs to be fixed or factored out
-    perform_runtime_config "${site_url}" || printf "\n\nWARNING: runtime config failed, ignoring\n\n"
+    perform_runtime_config "${site}" || printf "\n\nWARNING: runtime config failed, ignoring\n\n"
```
Comment (birkland) [inline drupal/rootfs/etc/cont-init.d/99-custom-setup.sh:165]: Great - can you remove the `|| printf ...` part?  Now that it is fixed, we'd want this to fail if `perform_runtime_config` fails.  Prior to this fix, the `|| printf` was in place as a temporary workaround to allow `perform_runtime_config` to fail, without terminating the script

**Review by birkland — CHANGES_REQUESTED** [review]
Great - just remove the `|| printf` part, as this PR makes it no longer needed

File: drupal/rootfs/etc/cont-init.d/99-custom-setup.sh (hunk 1 above)
Comment (emetsger) [reply drupal/rootfs/etc/cont-init.d/99-custom-setup.sh]: yup! good catch.

**Review by birkland — APPROVED** [review]
